// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
    return FirebaseOptions(
      apiKey: "AIzaSyBja4lAq9oGz-pEGALZgmUGyICgoKIrDxI",
      authDomain: "smartcard-8ebea.firebaseapp.com",
      projectId: "smartcard-8ebea",
      storageBucket: "smartcard-8ebea.firebasestorage.app",
      messagingSenderId: "106105989505",
      appId: "1:106105989505:web:a1ae0657f831ad8c632080",
      measurementId: "G-Y4JPTWBH8L",
    );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTATbljw-gXYVMOQR24JWZlXVfFZ-fy6c',
    appId: '1:106105989505:android:3eedc32ae11c404b632080',
    messagingSenderId: '106105989505',
    projectId: 'smartcard-8ebea',
    storageBucket: 'smartcard-8ebea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMhr8eLx1Cb5he-JCKnIk8AxLGclyLebQ',
    appId: '1:106105989505:ios:dc2ddfe15d0d4bf0632080',
    messagingSenderId: '106105989505',
    projectId: 'smartcard-8ebea',
    storageBucket: 'smartcard-8ebea.firebasestorage.app',
    iosBundleId: 'com.example.smartCard',
  );
}
