// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQLWlfqnxqNCoHxTh6RL0ZSXZeJ7legz0',
    appId: '1:731351689459:web:1331697726d9aab1092f86',
    messagingSenderId: '731351689459',
    projectId: 'smartcard-475413',
    authDomain: 'smartcard-475413.firebaseapp.com',
    storageBucket: 'smartcard-475413.firebasestorage.app',
    measurementId: 'G-LHS2EQ9Z5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3HKHU8d_6ushUuIsKOl_xsGoW_JMdDuQ',
    appId: '1:731351689459:android:8bf928dc44741f14092f86',
    messagingSenderId: '731351689459',
    projectId: 'smartcard-475413',
    storageBucket: 'smartcard-475413.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEdW4ekrRZPzFD6e-HxWn3Wb56wTmzkC0',
    appId: '1:731351689459:ios:3628424c88803dbd092f86',
    messagingSenderId: '731351689459',
    projectId: 'smartcard-475413',
    storageBucket: 'smartcard-475413.firebasestorage.app',
    iosClientId: '731351689459-90enhp2m9m3kkk88ivul6pj5aqpji08k.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartCard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEdW4ekrRZPzFD6e-HxWn3Wb56wTmzkC0',
    appId: '1:731351689459:ios:3628424c88803dbd092f86',
    messagingSenderId: '731351689459',
    projectId: 'smartcard-475413',
    storageBucket: 'smartcard-475413.firebasestorage.app',
    iosClientId: '731351689459-90enhp2m9m3kkk88ivul6pj5aqpji08k.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartCard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQLWlfqnxqNCoHxTh6RL0ZSXZeJ7legz0',
    appId: '1:731351689459:web:d26f1e6d73a6ca21092f86',
    messagingSenderId: '731351689459',
    projectId: 'smartcard-475413',
    authDomain: 'smartcard-475413.firebaseapp.com',
    storageBucket: 'smartcard-475413.firebasestorage.app',
    measurementId: 'G-YWZLP0FZGC',
  );

}